version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn build && yarn serve"
    environment:
      PORT: 4000
      NODE_ENV: production
    env_file:
      - .env
