version: "3.3"

services:
  nginx:
    container_name: 'nginx-service'
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - app
    restart: always

  payload:
    container_name: 'payload-cms'
    image: ghcr.io/n30w/tab-sa-cms:dev
    ports:
      - 4000:4000
    networks:
      - app
    restart: always
    env_file:
      - ./.env

networks:
  app:
    driver: bridge
